import { User, Tenant, Course, Enrollment, Analytics, Lesson } from '@/lib/types';

// Mock Tenants
export const mockTenants: Tenant[] = [
  {
    id: 'tenant-1',
    name: 'TechCorp Academy',
    domain: 'techcorp.academy',
    logo: '/api/placeholder/120/40',
    primaryColor: '#3B82F6',
    secondaryColor: '#14B8A6',
    fontFamily: 'Inter',
    theme: 'dark',
    settings: {
      allowSelfRegistration: true,
      requireEmailVerification: false,
      defaultUserRole: 'learner',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'tenant-2',
    name: 'EduBright University',
    domain: 'edubright.edu',
    logo: '/api/placeholder/120/40',
    primaryColor: '#7C3AED',
    secondaryColor: '#06B6D4',
    fontFamily: 'Inter',
    theme: 'edu-bright',
    settings: {
      allowSelfRegistration: true,
      requireEmailVerification: true,
      defaultUserRole: 'learner',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@techcorp.academy',
    name: 'Admin User',
    role: 'admin',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
    tenantId: 'tenant-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    email: 'instructor@techcorp.academy',
    name: 'Jane Smith',
    role: 'instructor',
    avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
    tenantId: 'tenant-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-3',
    email: 'learner@techcorp.academy',
    name: 'John Doe',
    role: 'learner',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
    tenantId: 'tenant-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-4',
    email: 'admin@edubright.edu',
    name: 'Sarah Johnson',
    role: 'admin',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
    tenantId: 'tenant-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-5',
    email: 'instructor@edubright.edu',
    name: 'Mike Wilson',
    role: 'instructor',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
    tenantId: 'tenant-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock Lessons
export const mockLessons: Lesson[] = [
  // React Fundamentals lessons
  {
    id: 'lesson-1',
    title: 'Introduction to React',
    description: 'Learn the basics of React and JSX',
    content: '<h1>Introduction to React</h1><p>React is a JavaScript library for building user interfaces...</p>',
    videoUrl: 'https://example.com/video1.mp4',
    duration: 25,
    order: 1,
    isPreview: true,
    courseId: 'course-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'lesson-2',
    title: 'Components and Props',
    description: 'Understanding React components and props',
    content: '<h1>Components and Props</h1><p>Components are the building blocks of React applications...</p>',
    videoUrl: 'https://example.com/video2.mp4',
    duration: 30,
    order: 2,
    isPreview: false,
    courseId: 'course-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'lesson-3',
    title: 'State and Event Handling',
    description: 'Managing component state and handling events',
    content: '<h1>State and Event Handling</h1><p>State allows components to create and manage their own data...</p>',
    videoUrl: 'https://example.com/video3.mp4',
    duration: 35,
    order: 3,
    isPreview: false,
    courseId: 'course-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // Node.js Backend lessons
  {
    id: 'lesson-4',
    title: 'Node.js Basics',
    description: 'Getting started with Node.js',
    content: '<h1>Node.js Basics</h1><p>Node.js is a JavaScript runtime built on Chrome V8 engine...</p>',
    videoUrl: 'https://example.com/video4.mp4',
    duration: 20,
    order: 1,
    isPreview: true,
    courseId: 'course-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'lesson-5',
    title: 'Express.js Framework',
    description: 'Building web applications with Express.js',
    content: '<h1>Express.js Framework</h1><p>Express.js is a minimal and flexible Node.js web application framework...</p>',
    videoUrl: 'https://example.com/video5.mp4',
    duration: 40,
    order: 2,
    isPreview: false,
    courseId: 'course-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock Courses
export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'React Fundamentals',
    description: 'Learn the basics of React including components, state, and props. Perfect for beginners looking to master modern web development.',
    thumbnail: 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
    price: 99.99,
    currency: 'USD',
    instructorId: 'user-2',
    tenantId: 'tenant-1',
    category: 'Web Development',
    level: 'beginner',
    duration: 90,
    isPublished: true,
    lessons: mockLessons.filter(l => l.courseId === 'course-1'),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-2',
    title: 'Node.js Backend Development',
    description: 'Master server-side JavaScript with Node.js and Express. Build scalable web applications and APIs.',
    thumbnail: 'https://images.pexels.com/photos/1181472/pexels-photo-1181472.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
    price: 149.99,
    currency: 'USD',
    instructorId: 'user-2',
    tenantId: 'tenant-1',
    category: 'Backend Development',
    level: 'intermediate',
    duration: 180,
    isPublished: true,
    lessons: mockLessons.filter(l => l.courseId === 'course-2'),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-3',
    title: 'Full Stack JavaScript',
    description: 'Complete full-stack development course covering React, Node.js, and database integration.',
    thumbnail: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
    price: 199.99,
    currency: 'USD',
    instructorId: 'user-2',
    tenantId: 'tenant-1',
    category: 'Full Stack Development',
    level: 'advanced',
    duration: 300,
    isPublished: true,
    lessons: [],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-4',
    title: 'Python for Data Science',
    description: 'Learn Python programming for data analysis and machine learning applications.',
    thumbnail: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
    price: 129.99,
    currency: 'USD',
    instructorId: 'user-5',
    tenantId: 'tenant-2',
    category: 'Data Science',
    level: 'beginner',
    duration: 240,
    isPublished: true,
    lessons: [],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-5',
    title: 'Machine Learning Fundamentals',
    description: 'Introduction to machine learning concepts and algorithms using Python.',
    thumbnail: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
    price: 179.99,
    currency: 'USD',
    instructorId: 'user-5',
    tenantId: 'tenant-2',
    category: 'Machine Learning',
    level: 'intermediate',
    duration: 320,
    isPublished: true,
    lessons: [],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-6',
    title: 'Database Design and SQL',
    description: 'Master database design principles and SQL for data management.',
    thumbnail: 'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
    price: 89.99,
    currency: 'USD',
    instructorId: 'user-5',
    tenantId: 'tenant-2',
    category: 'Database',
    level: 'beginner',
    duration: 150,
    isPublished: true,
    lessons: [],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock Enrollments
export const mockEnrollments: Enrollment[] = [
  {
    id: 'enrollment-1',
    userId: 'user-3',
    courseId: 'course-1',
    status: 'active',
    progress: 66,
    enrolledAt: new Date('2024-01-15'),
    completedLessons: ['lesson-1', 'lesson-2'],
  },
  {
    id: 'enrollment-2',
    userId: 'user-3',
    courseId: 'course-2',
    status: 'completed',
    progress: 100,
    enrolledAt: new Date('2024-01-10'),
    completedAt: new Date('2024-02-15'),
    completedLessons: ['lesson-4', 'lesson-5'],
  },
];

// Mock Analytics
export const mockAnalytics: Analytics = {
  totalUsers: 15,
  totalCourses: 6,
  totalEnrollments: 45,
  revenue: 12450.50,
  enrollmentsByMonth: [
    { month: 'Jan', count: 8 },
    { month: 'Feb', count: 12 },
    { month: 'Mar', count: 15 },
    { month: 'Apr', count: 10 },
  ],
  courseCompletionRates: [
    { courseId: 'course-1', completionRate: 75 },
    { courseId: 'course-2', completionRate: 60 },
    { courseId: 'course-3', completionRate: 45 },
  ],
  topCourses: [
    { courseId: 'course-1', enrollments: 15 },
    { courseId: 'course-2', enrollments: 12 },
    { courseId: 'course-4', enrollments: 10 },
  ],
};